/*
 * This source file was generated by the Gradle 'init' task
 */
package trafficsim;

import java.util.Arrays;

public class Main {
    public static void main(String[] args) {
        System.out.print("\033[H\033[2J");  
        System.out.flush();  
        Traffic t = Traffic.startSim(Constants.lanes, Constants.cars, Constants.dt, Constants.simTime);
        System.out.println("Average Distance (ft): " + t.getAverageDistance());
        System.out.println("Max Distance (ft): " + t.getMaxDistance());
        System.out.println("Cars per Lane: " + Arrays.toString(t.carsPerLane()));
    }
}
